version: '3'

services:
  db:
    image: postgres
    container_name: "fs_db"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fs

  db-test:
    image: postgres
    container_name: "fs_db-tests"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fs
